# Generated by Django 3.2.6 on 2023-10-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('proveedor_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(default='c/f', max_length=100)),
                ('tipo_producto', models.CharField(max_length=100)),
            ],
        ),
    ]
