# Generated by Django 4.2.5 on 2023-10-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='tipo_producto',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
