# Generated by Django 3.2.6 on 2023-10-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
            preserve_default=False,
        ),
    ]
