# Generated by Django 4.2.5 on 2023-10-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0002_auto_20231012_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='img',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='medicamentos/'),
        ),
    ]
