# Generated by Django 3.2.6 on 2023-10-19 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_proveedor'),
        ('medicamento', '0004_alter_medicamento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
            preserve_default=False,
        ),
    ]
